services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=templateV1'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=yunhwan'
    ports:
      - '3306:3306'

